{
  "hash": "ea7557900909795a4b2f2c2441c69cce",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \" World Development dataset analysis\"\nauthor: \"Pinxuan He\"\ndate: \"2025-2-26\"\nformat:\n  html:\n    code-fold: true\n  pdf: default\nbibliography: references.bib\n---\n\n\n\n\n\n\n## 2. Load the dataset using R.\n\n\n\n\n\n::: {.cell}\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning: package 'tidyverse' was built under R version 4.3.3\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning: package 'ggplot2' was built under R version 4.3.3\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning: package 'tibble' was built under R version 4.3.2\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning: package 'tidyr' was built under R version 4.3.2\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning: package 'readr' was built under R version 4.3.2\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning: package 'purrr' was built under R version 4.3.2\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning: package 'dplyr' was built under R version 4.3.3\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning: package 'stringr' was built under R version 4.3.2\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning: package 'forcats' was built under R version 4.3.2\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning: package 'lubridate' was built under R version 4.3.2\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\n-- Attaching core tidyverse packages ------------------------ tidyverse 2.0.0 --\nv dplyr     1.1.4     v readr     2.1.4\nv forcats   1.0.0     v stringr   1.5.0\nv ggplot2   3.5.1     v tibble    3.2.1\nv lubridate 1.9.3     v tidyr     1.3.0\nv purrr     1.0.2     \n-- Conflicts ------------------------------------------ tidyverse_conflicts() --\nx dplyr::filter() masks stats::filter()\nx dplyr::lag()    masks stats::lag()\ni Use the conflicted package (<http://conflicted.r-lib.org/>) to force all conflicts to become errors\n```\n\n\n:::\n:::\n\n\n\n\n\n\n## 3.Conduct exploratory data analysis on at least three indicators of your choice. Summarise your findings in markdown sections.\n- Summary Statistics\n\n\n\n\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n\n```\n    Min.  1st Qu.   Median     Mean  3rd Qu.     Max.     NA's \n   250.6   2599.8   7606.2  20520.3  27542.2 226052.0       10 \n```\n\n\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\n   Min. 1st Qu.  Median    Mean 3rd Qu.    Max.    NA's \n  53.00   66.78   73.51   72.42   78.47   85.38       8 \n```\n\n\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\n     Min.   1st Qu.    Median      Mean   3rd Qu.      Max. \n9.992e+03 8.216e+05 6.664e+06 3.671e+07 2.601e+07 1.425e+09 \n```\n\n\n:::\n:::\n\n\n\n\n\nThe summary provides key metrics (minimum, 1st quartile, median, mean, 3rd quartile, maximum) for each indicator. This helps us understand the central tendency and spread of the data.\n\n- Correlation Analysis\n\n\n\n\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n\n```\n                 gdp_per_capita life_expectancy total_population\ngdp_per_capita       1.00000000      0.64248552      -0.06151561\nlife_expectancy      0.64248552      1.00000000      -0.01445514\ntotal_population    -0.06151561     -0.01445514       1.00000000\n```\n\n\n:::\n:::\n\n\n\n\n\nThe correlation matrix shows the linear relationships between the variables. For example, a positive correlation between GDP per Capita and Life Expectancy might suggest that countries with higher incomes tend to have longer life expectancies.\n\nThe correlation matrix shows a moderate positive relationship between GDP per capita and life expectancy (r ≈ 0.64), indicating that higher income levels are generally associated with longer life expectancies. In contrast, both GDP per capita and life expectancy have almost no relationship with total population (r ≈ -0.06 and r ≈ -0.01, respectively), suggesting that a country's population size does not significantly impact these measures.\n\n## 4.Create at least two different types of plots (e.g., bar chart, scatter plot) to represent your analysis. Use Quarto code chunks to embed these visualisations. Add a title and axis labels to each plot. Use Quarto to include a caption and a reference to the source of the data. Hide your code in the final document.\n\n- top 20 countries with the highest GDP per Capita\n\n\n\n\n\n::: {.cell fig-label='gdp_bar'}\n::: {.cell-output-display}\n![Figure 1: Bar chart of GDP per Capita by Country (Top 20, 2022, in ascending order). Data source: World Development Indicators.](report_files/figure-pdf/unnamed-chunk-4-1.pdf)\n:::\n:::\n\n\n\n\n\n- Scatter plot of GDP per Capita vs. Life Expectancy\n\n\n\n\n\n::: {.cell fig-label='scatter_plot'}\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning: Removed 18 rows containing missing values or values outside the scale range\n(`geom_point()`).\n```\n\n\n:::\n\n::: {.cell-output-display}\n![Figure 2: Scatter plot of GDP per Capita vs. Life Expectancy (2022). Data source: World Development Indicators.](report_files/figure-pdf/unnamed-chunk-5-1.pdf)\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning: Removed 18 rows containing missing values or values outside the scale range\n(`geom_point()`).\n```\n\n\n:::\n:::\n\n\n\n\n\n\n## 5. Construct a table that highlights some key statistics from your analysis. Ensure the table is well-formatted and included in the report.\n\n\n\n\n\n::: {.cell fig-label='stats_table'}\n::: {.cell-output-display}\n\\begingroup\n\\fontsize{12.0pt}{14.4pt}\\selectfont\n\\begin{longtable}{lrrr}\n\\caption*{\n{\\large Key Statistics for Selected Indicators (2022)} \\\\ \n{\\small Data source: World Development Indicators}\n} \\\\ \n\\toprule\nIndicator & Median & Variance & Mean \\\\ \n\\midrule\\addlinespace[2.5pt]\nGDP per Capita & 7,606 & 938,855,045 & 20,520 \\\\ \nLife Expectancy & 74 & 59 & 72 \\\\ \n\\bottomrule\n\\end{longtable}\n\\endgroup\n\n\ndata source:World Development Indicators.\n:::\n:::\n\n\n\n\n\n\n## 6. Include cross-references to your figures and tables within the text. Demonstrate proper labeling and referencing techniques.\n\nIn this report, we presented a bar chart (Figure @ref(gdp_bar)) that displays the top 20 countries by GDP per Capita, a scatter plot (Figure @ref(scatter_plot)) that illustrates the relationship between Life Expectancy and GDP per Capita, and a summary table (Table @ref(stats_table)) showing the key statistics for these indicators. The cross-references ensure that readers can easily navigate to the relevant figures and table for further details.\n\n## 7. Add a bibliography using BibTeX (.bib). Cite at least two sources related to your analysis.\nThis report cites the findings from [@Smith2021] and [@Doe2020].\n",
    "supporting": [
      "report_files\\figure-pdf"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-in-header": [
        "\\usepackage{booktabs}\n\\usepackage{caption}\n\\usepackage{longtable}\n\\usepackage{colortbl}\n\\usepackage{array}\n\\usepackage{anyfontsize}\n\\usepackage{multirow}\n"
      ]
    },
    "engineDependencies": {},
    "preserve": null,
    "postProcess": false
  }
}