project:
  type: website
  output-dir: docs

format:
  html: default
  pdf: default

execute:
  echo: false

website:
  title: "World Development Indicators Analysis"
  navbar:
    left:
      - href: report.qmd
        text: Report
      - href: slides.qmd
        text: Presentation
